name: NiiniiwiPerma
api: "1.20"
version: "${version}"
main: com.spectrasonic.NiiniiwiPerma.Main
api-version: "1.20"
authors: [Spectrasonic]
commands:
  perma:
    description: Comando principal del plugin
    usage: /<command>
    aliases: [p]
permissions:
  niiniiwipermanent.version:
    description: Permiso para ver la versión del plugin
    default: true
  niiniiwipermanent.reload:
    description: Permiso para recargar la configuración del plugin
    default: op
  niiniiwipermanent.mechanic:
    description: Permiso para usar comandos de mecánicas
    default: op
  niiniiwipermanent.mechanic.mineancient:
    description: Permiso para habilitar/deshabilitar la minería de Ancient Debris
    default: op
